name: "Arduino Lint"
on:
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/arduino-lint-action@v1.0.2
        with:
          compliance: strict
          project-type: all
          recursive: true
